### ISSUE TITLE
does not work with sbt 1.1.0-RC1

### ISSUE THREAD

**Issue by xuwei-k** [xerial/sbt-pack#127]
https://github.com/sbt/sbt/issues/3788

```
[error] java.lang.ExceptionInInitializerError
[error] 	at xerial.sbt.pack.PackPlugin$.packSettings$lzycompute(PackPlugin.scala:113)
[error] 	at xerial.sbt.pack.PackPlugin$.packSettings(PackPlugin.scala:112)
[error] 	at xerial.sbt.pack.PackPlugin$.projectSettings$lzycompute(PackPlugin.scala:108)
[error] 	at xerial.sbt.pack.PackPlugin$.projectSettings(PackPlugin.scala:108)
[error] 	at sbt.internal.Load$.$anonfun$resolveProject$3(Load.scala:1025)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:352)
[error] 	at sbt.internal.Load$.autoPluginSettings$1(Load.scala:1025)
[error] 	at sbt.internal.Load$.expandSettings$1(Load.scala:1042)
[error] 	at sbt.internal.Load$.$anonfun$resolveProject$10(Load.scala:1045)
[error] 	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:56)
[error] 	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:64)
[error] 	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:38)
[error] 	at scala.collection.TraversableOnce.$div$colon(TraversableOnce.scala:151)
[error] 	at scala.collection.TraversableOnce.$div$colon$(TraversableOnce.scala:151)
[error] 	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
[error] 	at sbt.internal.Load$.expandSettings$1(Load.scala:1044)
[error] 	at sbt.internal.Load$.$anonfun$resolveProject$1(Load.scala:1048)
[error] 	at sbt.internal.Load$.timed(Load.scala:1343)
[error] 	at sbt.internal.Load$.resolveProject(Load.scala:1014)
[error] 	at sbt.internal.Load$.finalizeProject$1(Load.scala:864)
[error] 	at sbt.internal.Load$.$anonfun$loadTransitive$15(Load.scala:958)
[error] 	at sbt.internal.Load$.timed(Load.scala:1343)
[error] 	at sbt.internal.Load$.loadTransitive(Load.scala:958)
[error] 	at sbt.internal.Load$.loadProjects$1(Load.scala:714)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$10(Load.scala:717)
[error] 	at sbt.internal.Load$.timed(Load.scala:1343)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:717)
[error] 	at sbt.internal.Load$.timed(Load.scala:1343)
[error] 	at sbt.internal.Load$.loadUnit(Load.scala:677)
[error] 	at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:477)
[error] 	at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:158)
[error] 	at sbt.internal.BuildLoader.apply(BuildLoader.scala:223)
[error] 	at sbt.internal.Load$.loadURI$1(Load.scala:539)
[error] 	at sbt.internal.Load$.loadAll(Load.scala:555)
[error] 	at sbt.internal.Load$.loadURI(Load.scala:485)
[error] 	at sbt.internal.Load$.load(Load.scala:464)
[error] 	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:253)
[error] 	at sbt.internal.Load$.timed(Load.scala:1343)
[error] 	at sbt.internal.Load$.apply(Load.scala:253)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:69)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:707)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:707)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:680)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:134)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:130)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:153)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:136)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:242)
[error] 	at sbt.State$$anon$1.process(State.scala:248)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:136)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:136)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:129)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:107)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:101)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:57)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:42)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:34)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:113)
[error] 	at sbt.xMain.run(Main.scala:76)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] Caused by: java.lang.IllegalArgumentException: requirement failed: A named attribute key must start with a lowercase letter: List of excluding files from the archive
[error] 	at scala.Predef$.require(Predef.scala:277)
[error] 	at sbt.internal.util.AttributeKey$$anon$1.<init>(Attributes.scala:102)
[error] 	at sbt.internal.util.AttributeKey$.make(Attributes.scala:98)
[error] 	at sbt.internal.util.AttributeKey$.apply(Attributes.scala:87)
[error] 	at sbt.internal.util.AttributeKey$.apply(Attributes.scala:76)
[error] 	at sbt.SettingKey$.apply(Structure.scala:673)
[error] 	at xerial.sbt.pack.PackPlugin$autoImport$.<init>(PackPlugin.scala:91)
[error] 	at xerial.sbt.pack.PackPlugin$autoImport$.<clinit>(PackPlugin.scala)
[error] 	at xerial.sbt.pack.PackPlugin$.packSettings$lzycompute(PackPlugin.scala:113)
[error] 	at xerial.sbt.pack.PackPlugin$.packSettings(PackPlugin.scala:112)
[error] 	at xerial.sbt.pack.PackPlugin$.projectSettings$lzycompute(PackPlugin.scala:108)
[error] 	at xerial.sbt.pack.PackPlugin$.projectSettings(PackPlugin.scala:108)
[error] 	at sbt.internal.Load$.$anonfun$resolveProject$3(Load.scala:1025)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:352)
[error] 	at sbt.internal.Load$.autoPluginSettings$1(Load.scala:1025)
[error] 	at sbt.internal.Load$.expandSettings$1(Load.scala:1042)
[error] 	at sbt.internal.Load$.$anonfun$resolveProject$10(Load.scala:1045)
[error] 	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:56)
[error] 	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:64)
[error] 	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:38)
[error] 	at scala.collection.TraversableOnce.$div$colon(TraversableOnce.scala:151)
[error] 	at scala.collection.TraversableOnce.$div$colon$(TraversableOnce.scala:151)
[error] 	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
[error] 	at sbt.internal.Load$.expandSettings$1(Load.scala:1044)
[error] 	at sbt.internal.Load$.$anonfun$resolveProject$1(Load.scala:1048)
[error] 	at sbt.internal.Load$.timed(Load.scala:1343)
[error] 	at sbt.internal.Load$.resolveProject(Load.scala:1014)
[error] 	at sbt.internal.Load$.finalizeProject$1(Load.scala:864)
[error] 	at sbt.internal.Load$.$anonfun$loadTransitive$15(Load.scala:958)
[error] 	at sbt.internal.Load$.timed(Load.scala:1343)
[error] 	at sbt.internal.Load$.loadTransitive(Load.scala:958)
[error] 	at sbt.internal.Load$.loadProjects$1(Load.scala:714)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$10(Load.scala:717)
[error] 	at sbt.internal.Load$.timed(Load.scala:1343)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:717)
[error] 	at sbt.internal.Load$.timed(Load.scala:1343)
[error] 	at sbt.internal.Load$.loadUnit(Load.scala:677)
[error] 	at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:477)
[error] 	at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:158)
[error] 	at sbt.internal.BuildLoader.apply(BuildLoader.scala:223)
[error] 	at sbt.internal.Load$.loadURI$1(Load.scala:539)
[error] 	at sbt.internal.Load$.loadAll(Load.scala:555)
[error] 	at sbt.internal.Load$.loadURI(Load.scala:485)
[error] 	at sbt.internal.Load$.load(Load.scala:464)
[error] 	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:253)
[error] 	at sbt.internal.Load$.timed(Load.scala:1343)
[error] 	at sbt.internal.Load$.apply(Load.scala:253)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:69)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:707)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:707)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:680)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:134)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:130)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:153)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:136)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:242)
[error] 	at sbt.State$$anon$1.process(State.scala:248)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:136)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:136)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:129)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:107)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:101)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:57)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:42)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:34)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:113)
[error] 	at sbt.xMain.run(Main.scala:76)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.ExceptionInInitializerError
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

**Comment by eed3si9n** [comment]
See https://github.com/xerial/sbt-pack/blob/0.9.2/src/main/scala/xerial/sbt/pack/PackPlugin.scala#L89-L96


```scala

    val packArchivePrefix      = SettingKey[String]("prefix of (prefix)-(version).(format) archive file name")
    val packArchiveName        = SettingKey[String]("archive file name. Default is (project-name)-(version)")
    val packArchiveStem        = SettingKey[String]("directory name within the archive. Default is (archive-name)")
    val packArchiveExcludes    = SettingKey[Seq[String]]("List of excluding files from the archive")
    val packArchiveTgzArtifact = SettingKey[Artifact]("tar.gz archive artifact")
    val packArchiveTbzArtifact = SettingKey[Artifact]("tar.bz2 archive artifact")
    val packArchiveTxzArtifact = SettingKey[Artifact]("tar.xz archive artifact")
    val packArchiveZipArtifact = SettingKey[Artifact]("zip archive artifact")
```

I am guessing these should all be `settingKey` not `SettingKey(...)`.

**Comment by xerial** [comment]
OK. I'll try to fix this next week.

**Comment by xerial** [comment]
Fixed in sbt-pack 0.9.2. Thanks for reporting!

**Comment by danslapman** [comment]
Experiencing this issue with sbt 1.1.0

**Comment by xerial** [comment]
@danslapman We are using sbt-pack 0.10.1 with sbt 1.1.0 without this problem. Which version are you using?

**Comment by danslapman** [comment]
Ouch, `0.10.1`, got it. I did use `0.9.2`

**Comment by nhooey** [comment]
@xerial Should the error message be more useful and actually report what "named attribute" it's referring to?

**Comment by xerial** [comment]
@nhooey I'm not 100% sure, but I guess it's difficult because the error is thrown inside sbt.

**Comment by vincentwoo** [comment]
Has there been any movement on this? This is a blocking issue for using sbt-pack with newer versions of sbt (which is necessary for using Java 10).
