### ISSUE TITLE
PackArchive fails on "too many open files"

### ISSUE THREAD

**Issue by dpennell** [xerial/sbt-pack#88]
It looks like PackArchive.scala:50 opens files, but never closes.

java.io.FileNotFoundException: /home/sherpa/workspace/cloud/com.ibm.csi.npm.ui/target/pack/VERSION (Too many open files)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:212)
	at java.io.FileInputStream.<init>(FileInputStream.java:152)
	at xerial.sbt.PackArchive$$anonfun$createArchive$1$$anonfun$xerial$sbt$PackArchive$class$$anonfun$$addFilesToArchive$1$3.apply(PackArchive.scala:50)
	at xerial.sbt.PackArchive$$anonfun$createArchive$1$$anonfun$xerial$sbt$PackArchive$class$$anonfun$$addFilesToArchive$1$3.apply(PackArchive.scala:44)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at xerial.sbt.PackArchive$$anonfun$createArchive$1.xerial$sbt$PackArchive$class$$anonfun$$addFilesToArchive$1(PackArchive.scala:44)
	at xerial.sbt.PackArchive$$anonfun$createArchive$1.apply(PackArchive.scala:54)
	at xerial.sbt.PackArchive$$anonfun$createArchive$1.apply(PackArchive.scala:31)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:267)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1143)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:618)
	at java.lang.Thread.run(Thread.java:785)

**Comment by xerial** [comment]
Thanks for reporting. Need to check file.close is properly called.
